# Generated by Django 4.2.2 on 2023-07-29 22:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64, null=True)),
                ('data', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/music'), upload_to='')),
                ('photo', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/image'), upload_to='')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
