# Generated by Django 4.2.2 on 2023-07-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_track_login_track_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='data',
            new_name='file',
        ),
    ]
