# Generated by Django 4.2.2 on 2023-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.BooleanField(default=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
