# Generated by Django 4.2.2 on 2023-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
