# Generated by Django 4.2.2 on 2023-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_id_alter_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('login', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
